[build]
  command = "next build"
  publish = ".next"

# Configuración para Next.js App Router
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirecciones para SPA y rutas dinámicas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
