[build]
  command = "pnpm install --no-frozen-lockfile && next build"
  publish = ".next"
  environment = { NETLIFY_USE_PNPM = "true", NETLIFY_PNPM_FLAGS = "--no-frozen-lockfile" }

[build.cache]
  enabled = false

# Configuración para Next.js App Router
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirecciones para SPA y rutas dinámicas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
